# Generated by Django 3.1.3 on 2020-11-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Новый промокод')),
                ('sale', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Новый промокод',
                'verbose_name_plural': 'Новые промокоды',
            },
        ),
    ]
