# Generated by Django 3.0.8 on 2020-10-25 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BezelMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Материал безеля')),
            ],
            options={
                'verbose_name': 'Материал безеля',
                'verbose_name_plural': 'Материал безеля',
            },
        ),
        migrations.CreateModel(
            name='BracerColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Цвет браслета')),
            ],
            options={
                'verbose_name': 'Цвет браслета',
                'verbose_name_plural': 'Цвет браслета',
            },
        ),
        migrations.CreateModel(
            name='BracerMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Материал браслета')),
            ],
            options={
                'verbose_name': 'Материал браслета',
                'verbose_name_plural': 'Материал браслета',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Бренд часов')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвет',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Состояние часов')),
            ],
            options={
                'verbose_name': 'Состояние часов',
                'verbose_name_plural': 'Состояние часов',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Комплектация')),
            ],
            options={
                'verbose_name': 'Комплектация',
                'verbose_name_plural': 'Комплектация',
            },
        ),
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Стекло')),
            ],
            options={
                'verbose_name': 'Стекло',
                'verbose_name_plural': 'Стекло',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материал',
            },
        ),
        migrations.CreateModel(
            name='MehType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип механизма')),
            ],
            options={
                'verbose_name': 'Тип механизма',
                'verbose_name_plural': 'Тип механизма',
            },
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Цифры')),
            ],
            options={
                'verbose_name': 'Цифры',
                'verbose_name_plural': 'Цифры',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='WatchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип часов')),
            ],
            options={
                'verbose_name': 'Тип часов',
                'verbose_name_plural': 'Типы часов',
            },
        ),
        migrations.CreateModel(
            name='Waterproof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Водонепраницаемость')),
            ],
            options={
                'verbose_name': 'Водонепраницаемость',
                'verbose_name_plural': 'Водонепраницаемость',
            },
        ),
        migrations.CreateModel(
            name='ZipMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Материал застёжки')),
            ],
            options={
                'verbose_name': 'Материал застёжки',
                'verbose_name_plural': 'Материал застёжки',
            },
        ),
        migrations.CreateModel(
            name='ZipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип застёжки')),
            ],
            options={
                'verbose_name': 'Тип застёжки',
                'verbose_name_plural': 'Тип застёжки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название часов')),
                ('id_number', models.CharField(max_length=30, verbose_name='Идентификационный номер')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('diameter1', models.IntegerField(blank=True, null=True, verbose_name='Диаметр1 мм')),
                ('diameter2', models.IntegerField(blank=True, null=True, verbose_name='Диаметр2 мм')),
                ('caliber', models.CharField(blank=True, max_length=30, null=True, verbose_name='Калибр/Механизм')),
                ('base_caliber', models.CharField(blank=True, max_length=30, null=True, verbose_name='Базовый калибр')),
                ('cruising_range', models.CharField(blank=True, max_length=30, null=True, verbose_name='Запас хода')),
                ('stones', models.CharField(blank=True, max_length=30, null=True, verbose_name='Количество камней')),
                ('vibration', models.CharField(blank=True, max_length=30, null=True, verbose_name='Частота вибрации баланса')),
                ('jenev_mark', models.BooleanField(blank=True, default=False, null=True, verbose_name='Женевское клеймо')),
                ('chronometer', models.BooleanField(blank=True, default=False, null=True, verbose_name='Хронометр')),
                ('master_chronometer', models.BooleanField(blank=True, default=False, null=True, verbose_name='Мастер хронометр')),
                ('photo', models.ImageField(blank=True, max_length=120, null=True, upload_to='img/admin_watch', verbose_name='Фото')),
                ('thickness', models.CharField(blank=True, max_length=30, null=True, verbose_name='Толщина')),
                ('back_cap', models.BooleanField(blank=True, default=False, null=True, verbose_name='Прозрачная задняя крышка')),
                ('jewelry', models.BooleanField(blank=True, default=False, null=True, verbose_name='Отделка драгоценными камнями')),
                ('spraying', models.BooleanField(blank=True, default=False, null=True, verbose_name='PVD/DLS напыление')),
                ('dial1', models.BooleanField(blank=True, default=False, null=True, verbose_name='Гильошированный циферблат')),
                ('dial2', models.BooleanField(blank=True, default=False, null=True, verbose_name='Ручное гильоширование')),
                ('dial3', models.BooleanField(blank=True, default=False, null=True, verbose_name='Люминисцентные цифры')),
                ('numbers1', models.BooleanField(blank=True, default=False, null=True, verbose_name='Центральная секундная стрелка')),
                ('numbers2', models.BooleanField(blank=True, default=False, null=True, verbose_name='Малый секундный циферблат')),
                ('numbers3', models.BooleanField(blank=True, default=False, null=True, verbose_name='Люминисцентные стрелки')),
                ('numbers4', models.BooleanField(blank=True, default=False, null=True, verbose_name='Стрелки из оксидированной стали')),
                ('func1', models.BooleanField(blank=True, default=False, null=True, verbose_name='Индикатор фазы луны')),
                ('func2', models.BooleanField(blank=True, default=False, null=True, verbose_name='Хронограф')),
                ('func3', models.BooleanField(blank=True, default=False, null=True, verbose_name='Flyback-функция')),
                ('func4', models.BooleanField(blank=True, default=False, null=True, verbose_name='Механизм боя')),
                ('func5', models.BooleanField(blank=True, default=False, null=True, verbose_name='Турбийон')),
                ('func6', models.BooleanField(blank=True, default=False, null=True, verbose_name='Индикатор дней недели')),
                ('func7', models.BooleanField(blank=True, default=False, null=True, verbose_name='Индикатор года')),
                ('func8', models.BooleanField(blank=True, default=False, null=True, verbose_name='Календарь на 4 года')),
                ('func9', models.BooleanField(blank=True, default=False, null=True, verbose_name='Будильник')),
                ('func10', models.BooleanField(blank=True, default=False, null=True, verbose_name='Уравнение времени')),
                ('func11', models.BooleanField(blank=True, default=False, null=True, verbose_name='Тахиметр')),
                ('func12', models.BooleanField(blank=True, default=False, null=True, verbose_name='Минутный репитор')),
                ('func13', models.BooleanField(blank=True, default=False, null=True, verbose_name='Сплит-хронограф')),
                ('func14', models.BooleanField(blank=True, default=False, null=True, verbose_name='Панорамная дата')),
                ('func15', models.BooleanField(blank=True, default=False, null=True, verbose_name='Репитер')),
                ('func16', models.BooleanField(blank=True, default=False, null=True, verbose_name='Дата')),
                ('func17', models.BooleanField(blank=True, default=False, null=True, verbose_name='Индикатор месяца')),
                ('func18', models.BooleanField(blank=True, default=False, null=True, verbose_name='Годовой календарь')),
                ('func19', models.BooleanField(blank=True, default=False, null=True, verbose_name='Вечный календарь')),
                ('func20', models.BooleanField(blank=True, default=False, null=True, verbose_name='GMT/две часовые зоны')),
                ('func21', models.BooleanField(blank=True, default=False, null=True, verbose_name='Прыгающий час')),
                ('bezel_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.BezelMaterial', verbose_name='Материал безеля')),
                ('bracer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.BracerMaterial', verbose_name='Материал браслета')),
                ('bracer_colour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.BracerColour', verbose_name='Цвет браслета')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.Brand', verbose_name='Бренд')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.Condition', verbose_name='Состояние часов')),
                ('corpus_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.Material', verbose_name='Материал корпуса')),
                ('dial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.Colour', verbose_name='Циферблат')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.Equipment', verbose_name='Комплектация')),
                ('glass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.Glass', verbose_name='Материал безеля')),
                ('meh_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.MehType', verbose_name='Тип механизма')),
                ('numbers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.Numbers', verbose_name='Цифры')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.Sex', verbose_name='Пол')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watch_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.WatchType', verbose_name='Тип часов')),
                ('waterproof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.Waterproof', verbose_name='Водонепроницаемость')),
                ('zip_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.ZipMaterial', verbose_name='Тип застёжки')),
                ('zip_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.ZipType', verbose_name='Материал застёжки')),
            ],
            options={
                'verbose_name': 'Часы',
                'verbose_name_plural': 'Часы',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prod.Product')),
            ],
        ),
    ]
