# Generated by Django 3.0.8 on 2020-10-27 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prod', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='watch_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.WatchType', verbose_name='Тип часов'),
        ),
        migrations.AddField(
            model_name='product',
            name='waterproof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.Waterproof', verbose_name='Водонепроницаемость'),
        ),
        migrations.AddField(
            model_name='product',
            name='zip_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.ZipMaterial', verbose_name='Тип застёжки'),
        ),
        migrations.AddField(
            model_name='product',
            name='zip_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.ZipType', verbose_name='Материал застёжки'),
        ),
        migrations.AddField(
            model_name='images',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prod.Product'),
        ),
    ]
